local function isAutomatedRun()
    for _, name in ipairs({
        "LAST_HAUL_SELF_TEST", "LAST_HAUL_CAPTURE", "LAST_HAUL_CAPTURE_HARVEST", "LAST_HAUL_CAPTURE_GAME",
        "LAST_HAUL_CAPTURE_FARM", "LAST_HAUL_CAPTURE_MINE", "LAST_HAUL_CAPTURE_WALL", "LAST_HAUL_CAPTURE_REPAIR",
        "LAST_HAUL_CAPTURE_META", "LAST_HAUL_CAPTURE_RESULTS", "LAST_HAUL_CAPTURE_UPGRADE", "LAST_HAUL_CAPTURE_CLEARCUT_INTRO", "LAST_HAUL_CAPTURE_LOBBY",
        "LAST_HAUL_CAPTURE_UNITS", "LAST_HAUL_CAPTURE_TEST_OPTIONS", "LAST_HAUL_CAPTURE_TURRET_PROMPT", "LAST_HAUL_CAPTURE_TURRET_PLACEMENT", "LAST_HAUL_CAPTURE_TURRET_UPGRADE", "LAST_HAUL_CAPTURE_CLEARCUT", "LAST_HAUL_CAPTURE_CLEARCUT_UPGRADE", "LAST_HAUL_CAPTURE_CLEARCUT_RESULTS", "LAST_HAUL_CAPTURE_CLEARCUT_THREATS", "LAST_HAUL_CAPTURE_CLEARCUT_BUILDS", "LAST_HAUL_CAPTURE_CLEARCUT_CHAR_SELECT", "LAST_HAUL_CAPTURE_CLEARCUT_FIREJOB", "LAST_HAUL_CAPTURE_CLEARCUT_DEVJOB", "LAST_HAUL_CAPTURE_CLEARCUT_COMBAT", "LAST_HAUL_CAPTURE_CLEARCUT_DEFEAT", "LAST_HAUL_CAPTURE_CLEARCUT_MILESTONE", "LAST_HAUL_CAPTURE_VEGAN_FORK", "LAST_HAUL_CAPTURE_ACHIEVEMENTS", "LAST_HAUL_CAPTURE_ACHIEVEMENT_POPUP", "LAST_HAUL_CAPTURE_SETTINGS", "LAST_HAUL_CAPTURE_CLEARCUT_MAP_SELECT", "LAST_HAUL_CAPTURE_CLEARCUT_BRIEFING", "LAST_HAUL_CAPTURE_CHARACTER_TRAITS", "LAST_HAUL_CAPTURE_TALL_FOREST", "LAST_HAUL_CAPTURE_TALL_FALL", "LAST_HAUL_CAPTURE_SCORE_FIREWORK"
    }) do
        if os.getenv(name) then return true end
    end
    return false
end

function love.conf(t)
    t.identity = "last-haul"
    t.version = "11.5"
    t.console = true
    t.window.title = "LAST HAUL — 전진 보급 로비"
    t.window.width = tonumber(os.getenv("LAST_HAUL_CAPTURE_WIDTH")) or 1280
    t.window.height = tonumber(os.getenv("LAST_HAUL_CAPTURE_HEIGHT")) or 720
    t.window.resizable = true
    t.window.minwidth = 960
    t.window.minheight = 540
    t.window.vsync = 1
    t.window.msaa = 0
    if isAutomatedRun() then t.window.visible, t.console = false, false end
end
