"""Bake fixed-model forest enemy rigs through the native-pixel material shader.

No game window. Requires Pillow, numpy, moderngl. Concepts remain untouched.
The output has one palette per species and one stable grid/foot anchor per rig.
"""
from pathlib import Path
import json
import math
from collections import deque
import numpy as np
import moderngl
from PIL import Image, ImageDraw, ImageFont
from build_cigarette_pixel_sprite import VERTEX, love_fragment, render

ROOT=Path(__file__).resolve().parents[1]


def make_palette(materials):
    colors=[]
    for value in materials:
        base=np.array([int(value[i:i+2],16) for i in (0,2,4)])/255
        for index in range(16):
            shade=index/15
            shadow=base*np.array([.26,.28,.34])
            highlight=np.minimum(1,base*1.20+np.array([.11,.10,.07]))
            colors.append(np.rint((shadow+(highlight-shadow)*shade)*255).astype(np.uint8))
    return np.array(colors)


def make_lut(ctx,palette):
    rows,cols=np.indices((1024,32))
    grid=np.stack([cols,rows%32,rows//32],axis=-1).reshape(-1,3).astype(np.float32)/31*255
    nearest=[]
    for start in range(0,len(grid),1024):
        delta=grid[start:start+1024,None,:]-palette[None,:,:]
        nearest.append(np.argmin((delta*delta*np.array([.30,.59,.11])).sum(axis=2),axis=1))
    data=palette[np.concatenate(nearest)].reshape(1024,32,3)
    texture=ctx.texture((32,1024),3,data.tobytes())
    texture.filter=(moderngl.NEAREST,moderngl.NEAREST)
    return texture


def connected_body_mask(source,crop):
    """Identify the specimen, excluding detached concept FX and adjacent cells."""
    x,y,w,h=crop
    pixels=np.asarray(source)[y:y+h,x:x+w]
    remaining=pixels[:,:,3]>=158
    biggest=[]
    for yy,xx in zip(*np.nonzero(remaining.copy())):
        if not remaining[yy,xx]: continue
        remaining[yy,xx]=False; stack=[(int(yy),int(xx))]; component=[]
        while stack:
            cy,cx=stack.pop(); component.append((cy,cx))
            for ny,nx in ((cy-1,cx),(cy+1,cx),(cy,cx-1),(cy,cx+1)):
                if 0<=ny<h and 0<=nx<w and remaining[ny,nx]:
                    remaining[ny,nx]=False; stack.append((ny,nx))
        if len(component)>len(biggest): biggest=component
    mask=np.zeros((h,w),dtype=np.uint8)
    for yy,xx in biggest: mask[yy,xx]=255
    return mask


def main():
    manifest=json.loads((ROOT/'assets/enemies/forest-enemies-v1.json').read_text(encoding='utf-8'))
    source=Image.open(ROOT/manifest['source']).convert('RGBA')
    ctx=moderngl.create_standalone_context()
    texture=ctx.texture(source.size,4,source.tobytes())
    texture.filter=(moderngl.LINEAR,moderngl.LINEAR) # reconstruction only while authoring; final sprites use nearest
    program=ctx.program(vertex_shader=VERTEX,fragment_shader=love_fragment(ROOT/'assets/shaders/forest-enemy-bake.glsl'))
    program['paletteLut'].value=1; program['sourceMask'].value=2; program['sourceSize'].value=source.size
    outputs=[]; report=[]
    catalog=['-- Generated by scripts/build_forest_enemy_atlases.py; source manifest is assets/enemies/forest-enemies-v1.json.','return {']
    for entry in manifest['entries']:
        cell=entry['cell']; x,y,w,h=entry['crop']; foot=cell-8
        fit=min((cell-28)/w,(cell-28)/h)
        bw,bh=round(w*fit),round(h*fit)
        rect=((cell-bw)//2,foot-bh,bw,bh)
        palette=make_palette(entry['materials']); lut=make_lut(ctx,palette); lut.use(1)
        mask_data=connected_body_mask(source,entry['crop'])
        mask=ctx.texture((w,h),1,mask_data.tobytes()); mask.filter=(moderngl.NEAREST,moderngl.NEAREST); mask.use(2)
        program['sourceRect'].value=(x,y,w,h); program['bodyRect'].value=rect
        program['cellSize'].value=cell; program['rigKind'].value=entry['rig']
        atlas=Image.new('RGBA',(cell*6,cell*2)); frames=[]
        for row in range(2):
            for frame in range(6):
                program['actionRow'].value=row
                program['phase'].value=frame/(6 if row==0 else 5)
                image=render(ctx,program,(cell,cell),texture)
                assert image.getchannel('A').getbbox(),f'empty {entry["id"]} {row}:{frame}'
                assert set(image.getchannel('A').tobytes())=={0,255}
                atlas.paste(image,(frame*cell,row*cell)); frames.append(image)
        filename=f'{entry["id"]}-atlas-pixel-v1.png'
        path=ROOT/'assets/enemies/ingame'/filename; atlas.save(path)
        rgba=np.asarray(atlas); colors=np.unique(rgba[rgba[:,:,3]>0,:3],axis=0)
        assert 70<=len(colors)<=128,(entry['id'],len(colors))
        assert len({f.tobytes() for f in frames[:6]})==6,'rig has duplicate walk/idle frames'
        box=frames[0].getchannel('A').getbbox()
        foot=max(frame.getchannel('A').getbbox()[3] for frame in frames)
        content_height=box[3]-box[1]
        # Use the authored baseline rather than the transparent cell margin for scale.
        scale=entry['height']/content_height
        catalog.append(f'    {entry["id"]}={{file="{filename}",cell={cell},foot={foot},height={entry["height"]},contentHeight={content_height},scale={scale:.8f},rig={entry["rig"]}}},')
        report.append({'id':entry['id'],'cell':cell,'frames':12,'colors':len(colors),'bbox':box,'foot':foot,'worldHeight':entry['height'],'scale':scale})
        outputs.append((entry,frames[0],frames))
        lut.release(); mask.release()
        print(f'{entry["id"]}: {cell}x{cell} x12, {len(colors)} colors, height={entry["height"]}')
    catalog.append('}')
    (ROOT/'src/forest_enemy_catalog.lua').write_text('\n'.join(catalog)+'\n',encoding='utf-8')
    previews=ROOT/'docs/previews'; previews.mkdir(exist_ok=True)
    (previews/'forest-enemy-build-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
    font_path=ROOT/'assets/font-korean-regular.ttf'
    font=ImageFont.truetype(str(font_path),20)
    sheet=Image.new('RGB',(1200,1320),(43,50,38)); draw=ImageDraw.Draw(sheet)
    for i,(entry,image,frames) in enumerate(outputs):
        col,row=i%3,i//3; left,top=col*400,row*440
        preview=image.resize((360,360),Image.Resampling.NEAREST)
        sheet.paste(preview,(left+20,top+36),preview)
        draw.text((left+20,top+8),entry['name'],font=font,fill=(230,221,194))
        draw.text((left+20,top+405),f'{entry["cell"]} px | 12 frames',font=font,fill=(168,177,153))
    sheet.save(previews/'forest-enemies-pixel-v1.png')
    animation=[]
    for frame in range(6):
        canvas=Image.new('RGB',(900,900),(43,50,38))
        for i,(_,_,frames) in enumerate(outputs):
            image=frames[frame].resize((280,280),Image.Resampling.NEAREST)
            canvas.paste(image,((i%3)*300+10,(i//3)*300+10),image)
        animation.append(canvas)
    animation[0].save(previews/'forest-enemies-motion-v1.gif',save_all=True,append_images=animation[1:],duration=130,loop=0)
    print('FOREST_ENEMY_BAKE_OK',ctx.info['GL_RENDERER'])


if __name__=='__main__': main()
