"""Bake approved arcade models with native GLSL; never starts LÖVE.

ImageGen supplies fixed models, not independent animation frames. GPU removes
the monster board's explicit magenta key; the tree board has real RGBA alpha.
Pillow only packs GPU output and creates inspection sheets.
"""
from pathlib import Path
import json
import numpy as np
import moderngl
from PIL import Image, ImageDraw
from build_cigarette_pixel_sprite import VERTEX, love_fragment, render
from build_forest_enemy_atlases import make_palette, make_lut

ROOT = Path(__file__).resolve().parents[1]
TREES = [
    ('broadleaf', (193,208), ['798433','496029','a1a443','826032','bd843a','334121','584029','252c20']),
    ('pine', (151,226), ['496345','2c463d','6c814b','89723b','a2753b','273830','46543d','292b24']),
    ('birch', (144,216), ['85923b','526a2c','afad52','e1cba9','a8978b','71626a','403a3b','33452b']),
    ('maple', (170,226), ['b96732','db8137','884326','663826','926137','bb8548','463026','38281e']),
]
# Keep species identity and small arcade proportions. Width is visual only.
ENEMIES = [
    ('squirrel',0,0,128,43,1,['b96b25','d08b32','764326','efbd61','cc4824','573121','2a251e','87734b']),
    ('boar',1,0,128,64,1,['806043','a17b55','4d392b','e2cba2','cf5b2e','483e30','312921','786c57']),
    ('turret',2,0,128,56,2,['95546f','ba7390','64394f','d9b97e','a58355','574333','392c30','9c8770']),
    ('vineSprout',3,0,160,74,2,['9e4829','ca6630','e4ad45','637334','899047','3c4d28','613b29','302e20']),
    ('ent',0,1,256,140,2,['73803a','9e9c4c','48572b','80603c','aa824b','513f2d','e7b549','39332a']),
    ('reaper',2,1,160,75,2,['695762','8c737a','433947','332f37','c64a30','e28a45','504b4e','24252b']),
]

def bounds(source, cell, key):
    x,y,w,h = cell
    a = np.asarray(source)[y:y+h,x:x+w]
    visible = a[:,:,3] >= 180
    if key:
        rgb = a[:,:,:3].astype(float)/255
        visible &= ~((rgb[:,:,0] > rgb[:,:,1]*1.8+.18) & (rgb[:,:,2] > rgb[:,:,1]*1.8+.18))
    yy,xx = np.nonzero(visible)
    assert len(xx), cell
    return x+int(xx.min()), y+int(yy.min()), int(xx.max()-xx.min()+1), int(yy.max()-yy.min()+1)

def main():
    ctx = moderngl.create_standalone_context()
    shader = ctx.program(vertex_shader=VERTEX, fragment_shader=love_fragment(ROOT/'assets/shaders/forest-arcade-bake.glsl'))
    shader['paletteLut'].value = 1
    report = []; catalog = ['-- Generated by build_forest_arcade_assets.py. Approved arcade v3 only.', 'return {']
    inspection = Image.new('RGB',(1120,840),(53,62,38))
    pen = ImageDraw.Draw(inspection)
    for category,source_name,entries in [('trees','assets/trees/concepts/forest-cartoon-models-v3.png',TREES),('enemies','assets/enemies/concepts/forest-arcade-models-v3.png',ENEMIES)]:
        source = Image.open(ROOT/source_name).convert('RGBA')
        texture = ctx.texture(source.size,4,source.tobytes()); texture.filter=(moderngl.NEAREST,moderngl.NEAREST)
        shader['sourceSize'].value = source.size
        key = category == 'enemies'; shader['chromaKey'].value = float(key)
        cols = 4 if key else 2
        for i,entry in enumerate(entries):
            if key:
                name,col,row,cell,width,motion,materials = entry
                size=(cell,cell); foot=cell-8; count=12
            else:
                name,size,materials=entry; col,row=i%2,i//2; motion=0; count=1
                foot=round(size[1]*.91)
            x0=round(col*source.width/cols); x1=round((col+1)*source.width/cols)
            y0=round(row*source.height/2); y1=round((row+1)*source.height/2)
            crop=bounds(source,(x0,y0,x1-x0,y1-y0),key)
            fit=min((size[0]-12)/crop[2],(foot-8)/crop[3])
            bw,bh=round(crop[2]*fit),round(crop[3]*fit)
            shader['sourceRect'].value=crop; shader['bodyRect'].value=((size[0]-bw)//2,foot-bh,bw,bh)
            shader['outputSize'].value=size; shader['motion'].value=motion
            lut=make_lut(ctx,make_palette(materials)); lut.use(1)
            atlas=Image.new('RGBA',(size[0]*(6 if key else 1),size[1]*(2 if key else 1)))
            frames=[]
            for j in range(count):
                shader['actionRow'].value=float(j//6)
                shader['phase'].value=(j%6)/(5 if j>=6 else 6)
                frame=render(ctx,shader,size,texture); frames.append(frame)
                atlas.paste(frame,((j%6)*size[0],(j//6)*size[1]))
            colors={tuple(c) for c in np.asarray(atlas).reshape(-1,4)}; opaque={c[:3] for c in colors if c[3]}
            assert {c[3] for c in colors} == {0,255}
            assert 45<=len(opaque)<=128,(name,len(opaque))
            if key:
                file=f'assets/enemies/arcade/{name}-atlas-v3.png'
                catalog.append(f'    {name}={{file="{file}",cell={cell},foot={foot},width={width},bodyWidth={bw},height={bh},motion={motion},facing={-1 if name=="squirrel" else 1}}},')
            else: file=f'assets/trees/{name}-tree-cartoon-v3.png'
            atlas.save(ROOT/file)
            box=frames[0].getbbox()
            record=dict(id=name,category=category,file=file,size=atlas.size,colors=len(opaque),frames=count,foot=foot,bbox=box)
            report.append(record)
            print(record)
            # Inspection only: enlarge native pixels, never reuse this in game.
            preview=frames[0]
            if not key:
                left,top=i*280,10
                show=preview.resize((size[0],size[1]),Image.Resampling.NEAREST)
            else:
                preview_index=6 if name=='reaper' else i
                left,top=(preview_index%4)*280,280+(preview_index//4)*280
                show=preview.resize((240,240),Image.Resampling.NEAREST)
            inspection.paste(show,(left+20,top+22),show); pen.text((left+20,top+4),name,fill=(234,219,182))
            lut.release()
        texture.release()
    siege_file='assets/enemies/arcade/worldtree-siege-atlas-v1.png'
    siege=Image.open(ROOT/siege_file).convert('RGBA')
    report.append(dict(id='worldtree',category='enemies',file=siege_file,size=siege.size,colors=len(siege.getcolors(siege.width*siege.height) or []),frames=12,foot=992,bbox=siege.crop((0,0,1024,1024)).getbbox()))
    show=siege.crop((0,0,1024,1024)).resize((240,240),Image.Resampling.NEAREST)
    inspection.paste(show,(300,582),show);pen.text((300,564),'worldtree siege',fill=(234,219,182))
    catalog.append('    planter={file="assets/enemies/arcade/planter-forest-atlas-v3.png",cell=256,foot=248,width=68,bodyWidth=182,height=190,motion=2,facing=1},')
    catalog.append('    planter_forest={file="assets/enemies/arcade/planter-forest-atlas-v3.png",cell=256,foot=248,width=68,bodyWidth=182,height=190,motion=2,facing=1},')
    catalog.append('    planter_mangrove={file="assets/enemies/arcade/planter-mangrove-atlas-v3.png",cell=256,foot=248,width=70,bodyWidth=176,height=190,motion=2,facing=1},')
    catalog.append('    planter_madagascar={file="assets/enemies/arcade/planter-madagascar-atlas-v3.png",cell=256,foot=248,width=72,bodyWidth=190,height=190,motion=2,facing=1},')
    catalog.append('    planter_island={file="assets/enemies/arcade/planter-island-atlas-v3.png",cell=256,foot=248,width=74,bodyWidth=190,height=164,motion=2,facing=1},')
    catalog.append('    worldtree={file="assets/enemies/arcade/worldtree-siege-atlas-v1.png",cell=1024,foot=992,width=1050,bodyWidth=639,height=960,motion=2,facing=1,siege=true},')
    catalog.append('}')
    (ROOT/'src/forest_arcade_catalog.lua').write_text('\n'.join(catalog)+'\n',encoding='utf-8')
    (ROOT/'docs/previews/forest-arcade-v3-build.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
    inspection.save(ROOT/'docs/previews/forest-arcade-v3-assets.png')
    print('FOREST_ARCADE_GPU_OK',ctx.info['GL_RENDERER'])

if __name__ == '__main__': main()
