package.path="./?.lua;./?/init.lua;"..package.path
love={graphics={getDimensions=function()return 1280,720 end},math={random=function(a,b)return 0 end}}
local Camera=require("src.camera")
local Projection=require("src.world_projection")
local cam=Camera.new(500,400)
cam.renderX,cam.renderY,cam.renderZoom,cam.roll,cam.pitch=500,400,1.2,.013,.76
cam.perspective=true
local wx0,wy0=742,533
local sx,sy,perspective=cam:worldToScreen(wx0,wy0)
local wx,wy=cam:screenToWorld(sx,sy)
assert(math.abs(wx-wx0)<.001 and math.abs(wy-wy0)<.001,"2.5D projection input inverse drifted")
local topScale=Projection.factor(0,720,.76)
local bottomScale=Projection.factor(720,720,.76)
assert(topScale<.9 and bottomScale>1.05 and bottomScale>topScale,"perspective scale range drifted")
local ax=cam:worldToScreen(400,260)
local bx=cam:worldToScreen(600,260)
local cx=cam:worldToScreen(400,650)
local dx=cam:worldToScreen(600,650)
assert(dx-cx>bx-ax,"distant X spacing is not narrower than foreground spacing")
local left,top,right,bottom=cam:visibleBounds()
assert(left<right and top<bottom,"projected visible bounds invalid")
local game=assert(io.open("src/game.lua","rb")):read("*a")
local projection=assert(io.open("src/world_projection.lua","rb")):read("*a")
assert(game:find("WorldProjection.begin",1,true) and game:find("WorldProjection.finish",1,true),"world projection render pass missing")
assert(not game:find("CameraDepthArt",1,true),"screen-space foreground layer returned")
assert(not projection:find("backdrop",1,true),"separate backdrop image returned")
assert(projection:find("canvas",1,true) and projection:find("mesh",1,true),"terrain and actors do not share one projection")
assert(projection:find("love.graphics.scale(uniform,uniform)",1,true),"billboard sprite aspect ratio is not uniform")
assert(game:find("WorldProjection.finish()",1,true)<game:find("WorldProjection.drawBillboards",1,true),"billboards are drawn before projected ground")
local world=assert(io.open("src/world.lua","rb")):read("*a")
assert(world:find("self.billboardQueue",1,true) and world:find("item.ground",1,true),"ground and billboard passes are not separated")
assert(game:find("self.camera.userZoom=userZoom",1,true) and game:find("self.camera.renderZoom=self.camera.zoom",1,true),"Ctrl+wheel 2.5D zoom missing")
print(string.format("CAMERA_25D_OK pitch=.76 inverse=exact scale=%.2f..%.2f spacing=projected ground=warped billboards=uniform",topScale,bottomScale))
