-- Generated by scripts/build_forest_enemy_atlases.py; source manifest is assets/enemies/forest-enemies-v1.json.
return {
    squirrel={file="squirrel-atlas-pixel-v1.png",cell=256,foot=241,height=54,contentHeight=212,scale=0.25471698,rig=0},
    boar={file="boar-atlas-pixel-v1.png",cell=256,foot=244,height=66,contentHeight=203,scale=0.32512315,rig=1},
    turret={file="turret-atlas-pixel-v1.png",cell=256,foot=240,height=76,contentHeight=205,scale=0.37073171,rig=2},
    vineSprout={file="vineSprout-atlas-pixel-v1.png",cell=256,foot=240,height=86,contentHeight=209,scale=0.41148325,rig=3},
    reaper={file="reaper-atlas-pixel-v1.png",cell=320,foot=303,height=120,contentHeight=279,scale=0.43010753,rig=4},
    ent={file="ent-atlas-pixel-v1.png",cell=384,foot=367,height=195,contentHeight=337,scale=0.57863501,rig=5},
    worldtree={file="worldtree-atlas-pixel-v1.png",cell=512,foot=492,height=300,contentHeight=472,scale=0.63559322,rig=6},
    squirrel_elite={file="squirrel_elite-atlas-pixel-v1.png",cell=256,foot=234,height=64,contentHeight=212,scale=0.30188679,rig=0},
    boar_elite={file="boar_elite-atlas-pixel-v1.png",cell=320,foot=302,height=80,contentHeight=266,scale=0.30075188,rig=1},
}
