-- Generated by build_forest_arcade_assets.py. Approved arcade v3 only.
return {
    squirrel={file="assets/enemies/arcade/squirrel-atlas-v3.png",cell=128,foot=120,width=43,bodyWidth=116,height=103,motion=1,facing=-1},
    boar={file="assets/enemies/arcade/boar-atlas-v3.png",cell=128,foot=120,width=64,bodyWidth=111,height=112,motion=1,facing=1},
    turret={file="assets/enemies/arcade/turret-atlas-v3.png",cell=128,foot=120,width=56,bodyWidth=116,height=112,motion=2,facing=1},
    vineSprout={file="assets/enemies/arcade/vineSprout-atlas-v3.png",cell=160,foot=152,width=74,bodyWidth=94,height=144,motion=2,facing=1},
    ent={file="assets/enemies/arcade/ent-atlas-v3.png",cell=256,foot=248,width=140,bodyWidth=238,height=240,motion=2,facing=1},
    reaper={file="assets/enemies/arcade/reaper-atlas-v3.png",cell=160,foot=152,width=75,bodyWidth=119,height=144,motion=2,facing=1},
    planter={file="assets/enemies/arcade/planter-forest-atlas-v3.png",cell=256,foot=248,width=68,bodyWidth=182,height=190,motion=0,facing=1,prism=true,prismRow=0,prismWidth=22,prismYOffset=29},
    planter_forest={file="assets/enemies/arcade/planter-forest-atlas-v3.png",cell=256,foot=248,width=68,bodyWidth=182,height=190,motion=0,facing=1,prism=true,prismRow=0,prismWidth=22,prismYOffset=29},
    planter_mangrove={file="assets/enemies/arcade/planter-mangrove-atlas-v3.png",cell=256,foot=248,width=70,bodyWidth=176,height=190,motion=0,facing=1,prism=true,prismRow=1,prismWidth=23,prismYOffset=31},
    planter_madagascar={file="assets/enemies/arcade/planter-madagascar-atlas-v3.png",cell=256,foot=248,width=72,bodyWidth=190,height=190,motion=0,facing=1,prism=true,prismRow=2,prismWidth=23,prismYOffset=32},
    planter_island={file="assets/enemies/arcade/planter-island-atlas-v3.png",cell=256,foot=248,width=74,bodyWidth=190,height=164,motion=0,facing=1,prism=true,prismRow=3,prismWidth=24,prismYOffset=29},
    worldtree={file="assets/enemies/arcade/worldtree-siege-atlas-v1.png",cell=1024,foot=992,width=1050,bodyWidth=639,height=960,motion=2,facing=1,siege=true},
}
