-- Generated by build_forest_arcade_assets.py. Approved arcade v3 only.
return {
    squirrel={file="assets/enemies/arcade/squirrel-atlas-v3.png",cell=128,foot=120,width=33,bodyWidth=116,height=103,motion=1,facing=-1},
    boar={file="assets/enemies/arcade/boar-atlas-v3.png",cell=128,foot=120,width=49,bodyWidth=111,height=112,motion=1,facing=1},
    turret={file="assets/enemies/arcade/turret-atlas-v3.png",cell=128,foot=120,width=43,bodyWidth=116,height=112,motion=2,facing=1},
    vineSprout={file="assets/enemies/arcade/vineSprout-atlas-v3.png",cell=160,foot=152,width=57,bodyWidth=94,height=144,motion=2,facing=1},
    ent={file="assets/enemies/arcade/ent-atlas-v3.png",cell=256,foot=248,width=108,bodyWidth=238,height=240,motion=2,facing=1},
    worldtree={file="assets/enemies/arcade/worldtree-atlas-v3.png",cell=320,foot=312,width=202,bodyWidth=276,height=304,motion=2,facing=1},
    reaper={file="assets/enemies/arcade/reaper-atlas-v3.png",cell=160,foot=152,width=58,bodyWidth=119,height=144,motion=2,facing=1},
}
